apiVersion: v1
kind: Secret
type: ibm/ibmc-s3fs
metadata:
  name: auth-secret
data:
  username: dG9rZW4=
  password: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnFkR2tpT2lJM1pEaGpNV1V5TUMwd05UaGlMVFZtWkRJdFlXWXhOQzAzTXpBMk9HTXlNamt6T1dZaUxDSnBjM01pT2lKeVpXZHBjM1J5ZVM1dVp5NWliSFZsYldsNExtNWxkQ0o5LjByNHNaUFV6ckR1M2ZmNHc0QnFFTGtoVl9Dc0kxZlVyYXZkc2RwYW5PM1k=