apiVersion: v1
kind: Pod
metadata: 
  name: v100-test-pod-pdube-1
  namespace: dlaas 
spec:
  containers: 
  - name: v100-test-container-pdube
    image: registry.ng.bluemix.net/dlaas_dev/caffe_gpu_1.0-py2:master-41
    imagePullPolicy: Always
    command: ["/bin/sh"]
    args: ["-c","tail -f /dev/null"]
    resources: 
      requests: 
        cpu: "1.0"
        alpha.kubernetes.io/nvidia-gpu: 1
        memory: 8Gi 
      limits:
        cpu: "1"
        alpha.kubernetes.io/nvidia-gpu: 1
        memory: 8Gi 
    volumeMounts:
    - mountPath: "/mnt/caffe-vgg-model"
      name: caffe-vgg-imagenet-model-cos 
    - mountPath: "/mnt/imagenet"
      name: imagenet   
    - mountPath: "/mnt/imagenet-results"
      name: imagenet-results
  imagePullSecrets:
  - name: bluemix-cr-ng 
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: gpu-task     
  volumes: 
  - name: caffe-vgg-imagenet-model-cos
    flexVolume:
      driver: "ibm/ibmc-s3fs"
      secretRef:
        name: s3fs-imagenet-pdube        
      options: 
        bucket: "caffe-vgg-imagenet-model-cos"
        endpoint: "https://s3-api.dal-us-geo.objectstorage.service.networklayer.com"
        region: "us-standard" 
        cache-size-gb: "4"
        chunk-size-mb: "55"
        parallel-count: "5"
  - name: imagenet
    flexVolume:
      driver: "ibm/ibmc-s3fs"
      secretRef: 
        name: s3fs-imagenet-pdube        
      options: 
        bucket: "imagenet"
        endpoint: "https://s3-api.dal-us-geo.objectstorage.service.networklayer.com"
        region: "us-standard" 
        cache-size-gb: "4"
        chunk-size-mb: "55"
        parallel-count: "5"
  - name: imagenet-results
    flexVolume:
      driver: "ibm/ibmc-s3fs"
      secretRef: 
        name: s3fs-imagenet-pdube        
      options: 
        bucket: "imagenet-results"
        endpoint: "https://s3-api.dal-us-geo.objectstorage.service.networklayer.com"
        region: "us-standard" 
        cache-size-gb: "0"
        chunk-size-mb: "55"
        parallel-count: "2"               
  nodeSelector:
    kubernetes.io/hostname: 10.177.1.249 
